# Generated by Django 3.1 on 2020-09-22 00:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0004_auto_20200906_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('land_price', models.IntegerField()),
                ('virtual_tour_url', models.URLField(blank=True)),
                ('land_dues', models.IntegerField(blank=True)),
                ('address', models.CharField(blank=True, max_length=350)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('land_size', models.IntegerField(blank=True)),
                ('describe_land', models.TextField(blank=True)),
                ('related_website', models.URLField(blank=True)),
                ('love_about_land', models.TextField(blank=True)),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lands', to='profiles.profile')),
                ('saves', models.ManyToManyField(related_name='land_saves', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaveLand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lands.land')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_lands', to='profiles.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpenDateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_day', models.CharField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=1)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_date_time', to='lands.land')),
            ],
        ),
        migrations.CreateModel(
            name='LandVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_video', models.FileField(blank=True, null=True, upload_to='land_videos')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_videos', to='lands.land')),
            ],
        ),
        migrations.CreateModel(
            name='LandReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='lands.land')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LandImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_image', models.ImageField(blank=True, null=True, upload_to='land_images')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_images', to='lands.land')),
            ],
        ),
        migrations.CreateModel(
            name='LandCoordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(blank=True)),
                ('latitude', models.FloatField(blank=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_coordinate', to='lands.land')),
            ],
        ),
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_numbers', to='lands.land')),
            ],
        ),
    ]
