# Generated by Django 3.1 on 2020-09-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landimage',
            name='land_image',
            field=models.ImageField(blank=True, null=True, upload_to='land_images/% Y/% m/% d/'),
        ),
        migrations.AlterField(
            model_name='landvideo',
            name='land_video',
            field=models.FileField(blank=True, null=True, upload_to='land_videos/% Y/% m/% d/'),
        ),
    ]
