# Generated by Django 3.1 on 2020-08-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200829_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/profile_pic.png', null=True, upload_to='profile_pics'),
        ),
    ]
