# Generated by Django 3.1 on 2020-09-28 07:05

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200906_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_images/default_profile_pic.png', null=True, upload_to=core.utils.profile_image_thumbnail),
        ),
    ]
