# Generated by Django 3.1 on 2020-08-29 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_price', models.IntegerField()),
                ('home_type', models.CharField(blank=True, max_length=250)),
                ('virtual_tour_url', models.URLField(blank=True)),
                ('hoa_dues', models.IntegerField(blank=True)),
                ('number_bedrooms', models.IntegerField(blank=True)),
                ('number_bathrooms', models.IntegerField(blank=True)),
                ('lot_size', models.IntegerField(blank=True)),
                ('year_built', models.IntegerField(blank=True)),
                ('describe_home', models.TextField(blank=True)),
                ('related_website', models.URLField(blank=True)),
                ('love_about_home', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpenDateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date_time', models.DateTimeField(blank=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_date_time', to='homes.home')),
            ],
        ),
        migrations.CreateModel(
            name='HomeLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.IntegerField(blank=True)),
                ('latitude', models.IntegerField(blank=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_location', to='homes.home')),
            ],
        ),
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_images', to='homes.home')),
            ],
        ),
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_number', to='homes.home')),
            ],
        ),
    ]
