# Generated by Django 3.1 on 2020-08-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opendatetime',
            name='end_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homeimage',
            name='home_image',
            field=models.ImageField(blank=True, null=True, upload_to='home_images'),
        ),
        migrations.AlterField(
            model_name='opendatetime',
            name='open_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
