# Generated by Django 3.1 on 2020-08-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_auto_20200829_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opendatetime',
            name='end_date_time',
        ),
        migrations.RemoveField(
            model_name='opendatetime',
            name='open_date_time',
        ),
        migrations.AddField(
            model_name='opendatetime',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opendatetime',
            name='open_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opendatetime',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
