# Generated by Django 3.1 on 2020-08-31 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200831_1915'),
        ('homes', '0003_auto_20200829_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='homes', to='profiles.profile'),
            preserve_default=False,
        ),
    ]
