# Generated by Django 3.1 on 2020-08-31 21:56

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0005_auto_20200831_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactnumber',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
