# Generated by Django 3.1 on 2020-09-01 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0007_homereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='SittingRoomFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitting_room_feature', models.CharField(blank=True, max_length=60, null=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitting_room_features', to='homes.home')),
            ],
        ),
        migrations.CreateModel(
            name='RoomFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_feature', models.CharField(blank=True, max_length=60, null=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bedroom_features', to='homes.home')),
            ],
        ),
        migrations.CreateModel(
            name='KitchenFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen_feature', models.CharField(blank=True, max_length=60, null=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_features', to='homes.home')),
            ],
        ),
    ]
