# Generated by Django 3.1 on 2020-09-02 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0008_kitchenfeature_roomfeature_sittingroomfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='address',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='roomfeature',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_features', to='homes.home'),
        ),
    ]
