# Generated by Django 3.1 on 2020-09-04 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0010_auto_20200902_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_homes', to='homes.home')),
            ],
        ),
    ]
