# Generated by Django 3.1 on 2020-09-05 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0003_auto_20200831_1915'),
        ('homes', '0011_savehome'),
    ]

    operations = [
        migrations.AddField(
            model_name='savehome',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='saved_homes', to='profiles.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savehome',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savehome',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.home'),
        ),
    ]
