# Generated by Django 3.1 on 2020-09-05 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0012_auto_20200905_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savehome',
            name='profile',
        ),
        migrations.AlterField(
            model_name='savehome',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_homes', to='homes.home'),
        ),
    ]
