# Generated by Django 3.1 on 2020-09-05 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200831_1915'),
        ('homes', '0013_auto_20200905_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='save',
            field=models.ManyToManyField(related_name='saves', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='savehome',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='saved_homes', to='profiles.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savehome',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.home'),
        ),
    ]
