# Generated by Django 3.1 on 2020-09-05 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0014_auto_20200905_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savehome',
            name='user',
        ),
    ]
