# Generated by Django 3.1 on 2020-09-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0015_remove_savehome_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='save',
            field=models.ManyToManyField(related_name='saves', to='homes.SaveHome'),
        ),
    ]
