# Generated by Django 3.1 on 2020-09-06 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0019_savehome_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opendatetime',
            old_name='open_date',
            new_name='open_day',
        ),
    ]
