# Generated by Django 3.1 on 2020-09-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0023_generalhomefeatures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalhomefeatures',
            name='home_feature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kitchenfeature',
            name='kitchen_feature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='roomfeature',
            name='room_feature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sittingroomfeature',
            name='sitting_room_feature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
