# Generated by Django 3.1 on 2020-09-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0025_home_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='city',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
