# Generated by Django 3.1 on 2020-09-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0026_home_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='home_status',
            field=models.CharField(blank=True, choices=[(0, 'For Rent'), (1, 'For Sale')], max_length=1),
        ),
    ]
