# Generated by Django 3.1 on 2020-09-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0027_home_home_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
