# Generated by Django 3.1 on 2020-09-22 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homes', '0030_auto_20200919_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactnumber',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_numbers', to='homes.home'),
        ),
        migrations.AlterField(
            model_name='home',
            name='saves',
            field=models.ManyToManyField(related_name='home_saves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homevideo',
            name='home_video',
            field=models.FileField(blank=True, null=True, upload_to='home_videos'),
        ),
    ]
