# Generated by Django 3.1 on 2020-09-23 00:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0031_auto_20200922_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeimage',
            name='home_image',
            field=models.ImageField(blank=True, null=True, upload_to='home_images/% Y/% m/% d/'),
        ),
        migrations.AlterField(
            model_name='homevideo',
            name='home_video',
            field=models.FileField(blank=True, null=True, upload_to='home_videos/% Y/% m/% d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
