# Generated by Django 3.1 on 2020-09-28 07:05

import core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0032_auto_20200923_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeimage',
            name='home_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.home_image_thumbnail),
        ),
        migrations.AlterField(
            model_name='homevideo',
            name='home_video',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.home_video_thumbnail, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MP4', 'm4v', 'webm', 'mkv', 'flv', 'flc', 'vob', 'ogv', 'ogg', 'drc', 'gif', 'gifv', 'mng', 'avi', 'MTS', 'M2TS', 'TS', 'mov', 'qt', 'wmv', 'yuv', 'rm', 'rmvb', 'viv', 'asf', 'amv', 'm4p', 'mpg', 'mp2', 'mpeg', 'mpe', 'mpv', 'm2v', 'svi', '3gp', '3g2', 'mxf', 'roq', 'nsv', 'f4v', 'f4p', 'f4a', 'f4b'], message='unsupported file format')]),
        ),
    ]
